language: python
os:
- linux
dist: trusty
python:
- '3.4'
- '3.5'
- '3.6'
before install:
- echo "$PATH"
install:
- pip install coveralls
script:
- python setup.py install
- nosetests --with-coverage --cover-package=sis ./tests/test_sis_package.py -v
after_success: coveralls
deploy:
  - provider: pypi
    user: NickWaters
    server: https://test.pypi.org/legacy/
    password:
      secure: "qc3DTCMxUfX45gz0d4nTknQFlF1ZsGYekgjqnEIInISW8tJzV+56++eZXsp6jhdoyg6+v2PAuVq5E4aJtKPiIIn539YePWTGNS0kozuwbGXgEGR3vIVMK+++KjZMvXSXFRYSqeJssJaBg2oVBdDmXBxl5FYYe7h/P1aVp5DeVMhRa4mvqlhcQ7Vk50V0IkWzJBC4j9R9nfO9NiwDyQp89wt+wa18OnadCQ9H6z03bb3afQn9od3mOLZfc+oMW3PWvitJnHP13Azofne15CSrPv+eBSBY+QMf0c2K8kSSW752nXHpvC2TB2k0iPiaRHw5Et0ffE0LLN0VWHqHZ900jy1ejfbfPiwoynJT/+R9DJGUvYL12IRF8BsVcZrl2DM8iQPbI0DnC9/gFmkYMYT4NDzFVDeh4emuYe/9ov5P+7a7k/O3XTqhlHNK/i0CH7wCQa1oJVzLDkrvogpinr1QQnnSPD1VMjZoLV00YwbpVss0pVXsGqYOHTOIVqJIRFLRqVcMYpX+gvH7YJEETOYT8TSq04t8+rqdGmW09IESHyI9ZXOviINcFVoPArBCBAwTW1o0aXVqWRMFd3WlQKNqxbM1moP8MCFJwNs1qKaLykpJ2OwzWtbhT96tyfbYNH6eE1k5JNhOSFZwAbUu6qkIVYlizeKKM3Ctz6ITlvjXJjw="